[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."generate"]
  timeout = 300

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
