[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."generate"]
  timeout = 60

[functions."generate-property"]
  timeout = 30

[functions."generate-property-background"]
  timeout = 900

[functions."read-maisoku-background"]
  timeout = 900

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
